site_name: Kev.in
repo_url: https://github.com/mlinke-ai/kev.in
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Manuals:
      - Users: "manuals/users.md"
      - Administrators: "manuals/administrators.md"
  - API:
      - User: "api/user.md"
      - Exercise: "api/exercise.md"
      - Login: "api/login.md"
      - Solution: "api/solution.md"
      - Config: "api/config.md"
  - License: "license.md"
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
